# Generated by Django 5.0 on 2026-07-24 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('music_file', models.FileField(upload_to='music/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='music_banners/')),
                ('category', models.CharField(choices=[('sleep', 'Sleep'), ('focus', 'Focus'), ('emotional_healing', 'Emotional Healing'), ('nature', 'Nature'), ('instrumental', 'Instrumental')], default='instrumental', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FavoritePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_playlist', to=settings.AUTH_USER_MODEL)),
                ('music', models.ManyToManyField(blank=True, related_name='favorited_by', to='music.music')),
            ],
        ),
    ]
